$ModelName "spectrobes/creatures/Komainu.mdl"
$CDMaterials "models\spectrobes\creatures\Komainu\"

$bodygroup body 
{
	studio "Komainu.smd"
	studio "Komainu_pirate.dmx"
	studio "Komainu_futball.dmx"
	studio "Komainu_Patchwork.dmx"
}



$sequence REF "Komainu.smd"

$TextureGroup "Normal" 
{
	{ "Komainu" }
	{ "Gold" 	}
	{ "Silver"	}
}
/*
$texturegroup "Promo"
{
	{ "Pirate" 	  }
	{ "FutBall"   }
	{ "Patchwork" }
}
*/