// Created by Crowbar 0.67

$ModelName "spectrobes/creatures/shakoblade.mdl"
$CDMaterials "models\spectrobes\creatures\shakoblade"

// $scale 10.0
$body "body" "shakoblade.smd"

$texturegroup "skins"
{
    { "katai" "gold" "face" "bodyA" "bodyB" }
    { "katai alt" "gold alt" "face alt" "bodyA alt" "bodyB alt" }
}


$Contents "solid"
$SurfaceProp "default"
$IllumPosition -0.007 -0.17 0.411
$CBox 0 0 0 0 0 0
$BBox -2.381 -1.349 -0.017 2.721 1.336 0.84


$sequence "idle" "shakoblade.smd"

