// Created by Crowbar 0.67

$ModelName "spectrobes/creatures/Spikanor.mdl"

$Body "body" "Spikanor.smd"


$SurfaceProp "default"

$Contents "solid"

$IllumPosition 0 -17.509 15.086

$CDMaterials "models\spectrobes\creatures\Spikanor\"

$TextureGroup "skinfamilies"
{
	{ "phong2" "phong3" "phong4" "phong1" }
	{ "phongB" "phongC" "phongD" "phongA" }
}

$CBox 0 0 0 0 0 0

$BBox -24.637 -25.994 -3.897 59.654 25.987 34.064


$sequence "idle" "spikanor.smd"
