$modelname "spectrobes/creatures/Tekka.mdl"
$cdmaterials "models/spectrobes/creatures/tekka"

$body Tekka "Tekka.dmx"

$sequence reference "Tekka"


$bodygroup "Lids" {
    studio "Tekka_Eyelid/MABU00.smd"
    studio "Tekka_Eyelid/MABU01.smd"
    studio "Tekka_Eyelid/MABU02.smd"
    studio "Tekka_Eyelid/MABU03.smd"
    blank
}


/*
$animation Ref "Tekka.dmx"
$sequence reference { "Ref" activity "ACT_idle" 1 }
*/


