$Modelname "spectrobes/creatures/Tekkadorax.mdl"
$cdmaterials "models/spectrobes/creatures/tekkadorax"

$body Tekkadorax "Tekkadorax.dmx"

$animation Ref "Tekkadorax.dmx"

$sequence reference {
    "Ref"
    activity "ACT_idle" 1
}

$texturegroup "skins" 
{
    { "S000C_00", "S000C_01", "S000C_02", "S000C_03", "S000C_04", "S000C_05" }
    { "S000C_00_B", "S000C_01_B", "S000C_02_B", "S000C_03_B", "S000C_04_B", "S000C_05_B" }
}