// Created by Crowbar 0.67

$ModelName "spectrobes/creatures/Hikolossa.mdl"

$body "body" "hikolossa_body.smd"


$BodyGroup "rotors"
{
	studio "hikolossa_rotors.smd"
	blank
}


$SurfaceProp "default"

$Contents "solid"

$IllumPosition 0 -4.105 9.474

$CDMaterials "models\spectrobes\creatures\Hikolossa\"

$CBox 0 0 0 0 0 0

$BBox -12.276 -21.268 -17.913 20.487 21.268 36.861


$sequence "idle" "hikolossa_body.smd"
