// Created by Crowbar 0.67

$ModelName "spectrobes/creatures/Leopuba.mdl"

$body "body" "leopuba.smd"


$SurfaceProp "default"

$Contents "solid"

$IllumPosition 0 0.784 12.377

$CDMaterials "models\spectrobes\creatures\Leopuba\"

$TextureGroup "skinfamilies"
{
	{ "leopuba"     }
	{ "leopubaRare" }
}

$CBox 0 0 0 0 0 0

$BBox -17.749 -4.402 -0.031 16.181 4.402 24.786


$sequence "idle" "Leopuba.smd"
