// Created by Crowbar 0.67

$ModelName "spectrobes/creatures/Spiko.mdl"

$BodyGroup "studio"
{
	studio "spiko.smd"
}


$SurfaceProp "default"

$Contents "solid"

$IllumPosition 9.564 0.009 7.916

$CDMaterials "models\spectrobes\creatures\spiko\"

$CBox 0 0 0 0 0 0

$BBox -9.912 -14.429 -1.07 9.894 33.556 16.903


/*
$Sequence "static" {
	"spiko_anims\static.smd"

}

/*
$Sequence "Idle" {
	"spiko_anims\Idle.smd"
	activity "ACT_IDLE" 1

	loop
}
